### ISSUE TITLE
"Object is not valid" on DC/OS 1.8.1

### ISSUE THREAD

**Issue by cgbaker** [GalacticFog/gestalt-dcos#6]
When attempting to launch gestalt-framework on DC/OS 1.8.1, provisioning the data service results in a failure, with the displayed error "Object is not valid". The cause is an issue with Marathon 1.3.0-RC4 in the DC/OS 1.8.1 beta. We're in the process of submitting a patch to Marathon, and potentially implementing a workaround in the launcher.

**Comment by cgbaker** [comment]
This was addressed in the following Marathon issue: 
https://github.com/mesosphere/marathon/pull/4185

The fix should be present in next Marathon release 1.3.0-RC5 in the DC/OS beta release, 1.8.2.

**Comment by cgbaker** [comment]
I've added a note to the front page about this issue... I'll close this bug once I've tested on the DCOS 1.8.2 release.

**Comment by shangd** [comment]
I just installed the latest DCOS (1.10.2) / marathon (1.5.3) and still having this error

```
[2017-12-19 06:34:21,138] [34mINFO [0;39m 192.168.65.111 - - [19/Dec/2017:06:34:21 +0000] "PUT //192.168.65.111:2642/v2/apps/gestalt-framework/data-0?force=true HTTP/1.1" 422 127 "-" "AHC/2.0"  (mesosphere.chaos.http.ChaosRequestLog:qtp424943893-51)
[2017-12-19 06:34:21,139] [31mWARN [0;39m Deployment failed for change: 2017-12-19T06:34:21.137Z (mesosphere.marathon.core.group.impl.GroupManagerImpl:ForkJoinPool-3-worker-5)
mesosphere.marathon.ValidationFailedException: Validation failed: Failure(Set(RuleViolation(App(/gestalt-framework/data-0,None,List(),1.15,1,None,Set(),Some(Container(DOCKER,Some(DockerContainer(None,None,true,galacticfog/postgres_repl:release-1.2.0,None,List(),None,false)),None,List(AppPersistentVolume(pgdata,PersistentVolume(None,1,None,Set()),RW)),Some(List(ContainerPortMapping(5432,Some(5432),Map(VIP_0 -> /gestalt-framework-data-primary:5432),Some(sql),tcp,0,List()))))),2.0,Set(),0.0,Map(POSTGRES_USER -> EnvVarValue(gestaltdev), POSTGRES_PASSWORD -> EnvVarValue(letmein), PGDATA -> EnvVarValue(/mnt/mesos/sandbox/pgdata), PGREPL_TOKEN -> EnvVarValue(iw4nn4b3likeu), PGREPL_ROLE -> EnvVarValue(PRIMARY)),,List(),Set(AppHealthCheck(None,300,None,30,4,None,None,Some(0),TCP,15,15)),1,Map(),3600,4096.0,0,None,List(Network(None,container/bridge,Map())),None,None,List(),Some(AppResidency(3600,WAIT_FOREVER)),true,Map(),Some(300),Some(UpgradeStrategy(0.0,0.5)),None,None,Some(2017-12-19T06:34:21.137Z),None,YOUNGEST_FIRST,Some(UnreachableEnabled(0,0)),None),unreachableStrategy must be disabled for resident tasks,Some(value))))
	at mesosphere.marathon.api.v2.Validation$class.validateOrThrow(Validation.scala:23)
```

I think it's saying you need to set "unreachableStrategy ": "disabled" in the json payload?

**Comment by cgbaker** [comment]
That's not a required field. That is a bug in the Marathon PUT payload, described here: 
https://jira.mesosphere.com/browse/MARATHON-7941

There is an updated launcher payload described here https://github.com/GalacticFog/gestalt-dcos/issues/7#issuecomment-349996649 which works around that issue, while we wait for a newer version of launcher to go into the Universe.
